name: docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  merge_group:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Bazelisk
        uses: bazel-contrib/setup-bazel@0.9.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Test and build docs
        run: bazel test --config=ci --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} //docs:docs_test //docs:docs_site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v6

      - name: Install Bazelisk
        uses: bazel-contrib/setup-bazel@0.9.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Deploy to GitHub Pages
        run: bazel run --config=ci --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} //docs:deploy_docs
